spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

openai:
  api:
    key: ${OPENAI_API_KEY:your-api-key-here}
    model: gpt-3.5-turbo
    timeout: 30
    max-tokens: 2000

server:
  port: 8080

# CORS 설정
cors:
  allowed-origins: http://localhost:5173

logging:
  level:
    com.fortune.app: DEBUG
    org.springframework.web: DEBUG
    root: INFO