spring:
  application:
    name: fortune-app

  profiles:
    active: dev

  # Spring AI OpenAI Configuration
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key-here}
      chat:
        options:
          model: gpt-3.5-turbo
          max-tokens: 2000
          temperature: 0.7

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.fortune.app: DEBUG
    org.springframework.web: DEBUG
    org.springframework.ai: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info

# CORS Configuration
cors:
  allowed-origins: http://localhost:5173,http://localhost:5174

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha