spring:
  datasource:
    url: jdbc:mysql://mysql:3306/fitness_tracker
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fitness_user
    password: fitness_password
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8080

logging:
  level:
    com.fitness.tracker: INFO
    root: WARN
  file:
    name: /var/log/fitness-tracker.log